---
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      action-packages:
        patterns:
          - "*"

  # Maintain dependencies for pip
  - package-ecosystem: "pip" #
    directory: "/plotting-service"
    schedule:
      interval: "daily"
    groups:
      python-packages:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/plotting-service"
    schedule:
      interval: "daily"
    groups:
      plotting-service-docker-image:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/data-viewer"
    schedule:
      interval: "daily"
    groups:
      data-viewer-docker-image:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/data-viewer"
    schedule:
      interval: "daily"
    groups:
      yarn-packages:
        patterns:
          - "*"