---
name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.5

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.WRITE_PACKAGE_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          file: ./plotting-service/Dockerfile
          context: ./plotting-service
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/plotting-service:${{ github.sha }}

  build-and-push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.5

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.WRITE_PACKAGE_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          file: ./data-viewer/Dockerfile
          context: ./data-viewer
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/data-viewer:${{ github.sha }}