---
name: Run tests

on: 
  push:

permissions:
  contents: read

jobs:
 tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v3.5.0

      - name: Set up python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v4.5.0
        with:
          python-version: '3.12'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install python dependencies
        run: |
          cd plotting-service
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install .[test]

      - name: Run python tests
        run: |
          cd plotting-service
          pytest test --random-order --random-order-bucket=global --cov --cov-report=xml
