---
on: push

permissions:
  contents: read

jobs:
  code-inspection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v3.5.0

      - name: Set up python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v4.5.0
        with:
          python-version: '3.12'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install python dependencies
        run: |
          cd plotting-service
          python -m pip install --upgrade pip
          python -m pip install .

      - name: Start backend
        run: |
          export CEPH_DIR=${{ GITHUB_WORKSPACE }}/plotting-service/test/test_ceph
          uvicorn plotting_service.plotting_api:app &

      - name: CD Dataviewer
        run: cd ../data-viewer

      - name: cypress-run
        uses: cypress-io/github-action@v6
        with:
          build: yarn build
          start: yarn start
