---
on: push

permissions:
  contents: read

jobs:
  code-inspection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v3.5.0

      - name: Set up python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v4.5.0
        with:
          python-version: '3.12'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install python dependencies
        run: |
          cd plotting-service
          python -m pip install --upgrade pip
          python -m pip install .

      - name: Start backend
        env:
          CEPH_DIR: /home/runner/work/plotting-service/plotting-service/plotting-service/test/test_ceph
        run: uvicorn plotting_service.plotting_api:app &

      - name: cypress-run
        uses: cypress-io/github-action@v6
        with:
          build: yarn build
          start: yarn start
          working-directory: data-viewer
          headed: true
          browser: firefox

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-snapshots
          path: data-viewer/cypress/screenshots
